export const FETCH_QUIZES_START = "FETCH_QUIZES_START";
export const FETCH_QUIZES_SUCCESS = "FETCH_QUIZES_SUCCESS";
export const FETCH_QUIZES_ERROR = "FETCH_QUIZES_ERROR";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCES";
export const ANSWER_CLICK_SUCCESS = "ANSWER_CLICK_SUCCESS";
export const ANSWER_CLICK_FINISH = "ANSWER_CLICK_FINISH";
export const ANSWER_CLICK_NEXT_QUESTION = "ANSWER_CLICK_NEXT_QUESTION";
export const ANSWER_CLICK_ERROR = "ANSWER_CLICK_ERROR";
export const ON_RETRY = "ON_RETRY";

export const ADD_QUESTION = "ADD_QUESTION";
export const RESET_CREATE_QUIZ = "RESET_CREATE_QUIZ";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
